Выполнена задача по спринту 4
bukhmillerEd/MovieQuiz-ios pull request #2
Opened 2023-01-10 12:46 UTC by bukhmillerEd

Задача по спринту 4

2023-01-10 20:36 UTC, IBDesignable requested changes
Есть недоработки по макету, а код хорош 
<img width="512" alt="Снимок экрана 2023-01-10 в 22 35 46" src="https://user-images.githubusercontent.com/121577115/211656471-51aaab37-3a04-4c27-a3a0-6d2786fee011.png">

2023-01-10 20:36 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +private let questions: [QuizQuestion] = [
глобальный контекст не принято использовать, давай переместим внутрь класса

2023-01-10 20:36 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 20
эту настройку можно один раз сделать - во вьюДидЛоад или на сториборде

2023-01-10 20:36 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.masksToBounds = true // даём разрешение на рисование рамки
эту настройку также можно проделать один раз

2023-01-10 20:36 UTC, IBDesignable commented on MovieQuiz/Resources/Info.plist
> +		<string>YS Display-Thin</string>
давай лишнее удалим

2023-01-11 14:21 UTC, bukhmillerEd commented
Добрый день! Есть вопросы по замечаниям, указанные в Я. Практикуме
1) установить кастомный шрифт на лейблы кнопок.
вроде установлен, или не правильно ?
<img width="1321" alt="Снимок экрана 2023-01-11 в 16 54 17" src="https://user-images.githubusercontent.com/89964543/211827750-3bedb8cf-92ae-42b9-9879-7ac318570247.png">

2) отсуп сверху у стека должен быть равен 10
Это отступ от внешнего стеквью до сейф арии ? Если да, то на будущее, как понять из макета, что именно 10 должно быть, в макете есть только размер от стэка с номером вопроса до верха экрана, и он равен 54

2023-01-11 19:12 UTC, IBDesignable commented
> установить кастомный шрифт на лейблы кнопок. вроде установлен, или не правильно ?

на сколько помню, в твоей работе отображались system шрифты, если все ок - на повторной проверке зачту

> отсуп сверху у стека должен быть равен 10
Это отступ от внешнего стеквью до сейф арии ? Если да, то на будущее, как понять из макета, что именно 10 должно быть, в макете есть только размер от стэка с номером вопроса до верха экрана, и он равен 54

от safearea — верно. ты можешь навести на объект с зажатой клавишей cmd – тогда будет подсвечиваться инфа поподробнее.

<img width="338" alt="Снимок экрана 2023-01-11 в 21 11 46" src="https://user-images.githubusercontent.com/121577115/211896695-fdf37a16-478f-487b-9e37-9d3e8713ff13.png">

2023-01-12 18:21 UTC, merged