Выполнено задание по спринту 5
bukhmillerEd/MovieQuiz-ios pull request #3
Opened 2023-02-07 18:12 UTC by bukhmillerEd

2023-02-08 16:45 UTC, protos17 requested changes

2023-02-08 16:45 UTC, protos17 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +class AlertPresenter {
Необходимо переименовать его в ResultAlertPresenter как в ТЗ и класс пометить как final

2023-02-08 16:45 UTC, protos17 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +  private weak var delegat: UIViewController?
Это особо ни на что не влияет, однако, стоит писать слова без ошибок - delegate

2023-02-08 16:45 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    let massage = "\(result.text)\n Количество сыгранных квизов: \(statisticService.gamesCount)\n Рекорд: \(statisticService.bestGame.correct) (\(statisticService.bestGame.date.dateTimeString))\n Сре
По своему опыту хочу сказать, что в таком случае лучше использовать многострочный вариант строки. Материал оставил в комментариях

2023-02-08 16:45 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +      text: "Рейтинг этого фильма больше чем 6?",
Эту многократно повторяющуюся строку лучше вынести в отделную константу и обращаться к ней, потому как если эта строка поменяется, тебе нужно будет заменить один раз, а не 10

2023-02-08 16:45 UTC, protos17 commented on MovieQuiz/Services/QuizStepViewModel.swift
> +import UIKit
В этом файле не используются элементы UIKit, его импорт избыточен

2023-02-08 16:45 UTC, protos17 commented on MovieQuiz/Services/StatisticService.swift
> +          print("Невозможно сохранить результат")
Советую использовать assertionFailure, это поможет в отладке и поиске багов

2023-02-10 08:26 UTC, bukhmillerEd commented on MovieQuiz/Services/QuizStepViewModel.swift
> +import UIKit
а разве тут не используется let image: UIImage ?

2023-02-10 08:29 UTC, protos17 commented on MovieQuiz/Services/QuizStepViewModel.swift
> +import UIKit
Да, согласен, упустил

2023-02-11 10:08 UTC, protos17 approved these changes

2023-02-11 10:08 UTC, protos17 commented on MovieQuiz/Services/QuestionFactory.swift
> +}
В целом логика написана нормально, но обрати внимание, что у тебя в каждом квизе 11 вопросов показывается (нумерация идет с 0 - 10). Можно улучшить тем, что индекс брать так: let index = randomIndices.removeFirst(), потому что они там уже в рандомном порядке, а у тебя из сета, в котором они в рандомном порядке берется рандомный индекс. Еще можно сделать массив с числами в случайном порядке Array(0..<questions.count).shuffled()  и тогда индекс брать  let index = randomIndices.removeLast()

2023-02-14 08:16 UTC, merged